// Static parameter mappings

export const PARAMETER_NAMES: Record<string, string> = {
  PFOA: "PFOA",
  PFHPA: "PFHPA",
  PFHXA: "PFHXA",
  PFPEA: "PFPEA",
  PFBA: "PFBA",
  PFBS: "PFBS",
  PFDODA: "PFDoDA",
  PFNA: "PFNA",
  PFDA: "PFDA",
  PFUNA: "PFUnA",
  PFHPS: "PFHpS",
  PFTRDA: "PFTrDA",
  PFDS: "PFDS",
  ASPFOS: "ASPFOS",
  PFOS: "PFOS",
  PFHXS: "PFHxS",
  PFPS: "PFPS",
  PFNS: "PFNS",
  PFUNDS: "PFUnDS",
  PFDODS: "PFDoDS",
  PFTRDS: "PFTrDS",
  SPFAS: "Somme des 20 PFAS",
  CLVYL: "Chlorure de vinyl monomère",
  NO3: "Nitrates (en NO3)",
  NO2: "Nitrites (en NO2)",
  NO3_NO2: "Nitrates/50 + Nitrites/3",
  AS: "Arsenic",
  PB: "Plomb",
  "14DAN": "1,4 dioxane",
  PCLAT: "Perchlorate",
  DIM2ESA: "CGA 354742",
  ESADIM2: "CGA 354742",
  ESADIM1: "CGA 369873",
  DIM1ESA: "CGA 369873",
  "471811R": "Chlorothalonil R471811",
  R471811: "Chlorothalonil R471811",
  DMTHESA: "Diméthénamide ESA",
  ESADMTH: "Diméthénamide ESA",
  DMTHOXA: "Diméthénamide OXA",
  OXADMTH: "Diméthénamide OXA",
  CETCESA: "ESA acetochlore",
  ESACETC: "ESA acetochlore",
  ESALCL: "ESA alachlore",
  LCLESA: "ESA alachlore",
  MTZCESA: "ESA metazachlore",
  ESAMTZC: "ESA metazachlore",
  ESAMTC: "ESA metolachlore",
  MTCESA: "ESA metolachlore",
  MTCNOA: "Metolachlor NOA 413173",
  NOAMTC: "Metolachlor NOA 413173",
  CETCOXA: "OXA acetochlore",
  OXACETC: "OXA acetochlore",
  OXAMTZC: "OXA metazachlore",
  MTZCOXA: "OXA metazachlore",
  OXAMTC: "OXA metolachlore",
  MTCOXA: "OXA metolachlore",
  "26DCB": "2,6 Dichlorobenzamide",
  CLDZ_D: "Chloridazone desphényl",
  CLDZ_MD: "Chloridazone méthyl desphényl",
  CLTHALS: "Chlorothalonil R417888",
  ESAFLU: "Flufenacet ESA",
  NDMS: "N,N-Dimethylsulfamide",
  OXALCL: "OXA alachlore",
  TERBMDE: "Terbuméton-désethyl",
  ENDOB: "Endosulfan béta",
  ENDOA: "Endosulfan alpha",
  DCPMU: "1-(3,4-dichlorophényl)-3-méthylurée",
  DCPU: "1-(3,4-dichlorophényl)-urée",
  IPPU: "1-(4-isopropylphenyl)-urée",
  MMTA: "2-amino-4-methoxy-6-methyl-1,3,5-triazine",
  "2ANIP": "2-amino-N-iso-propylbenzamide",
  ASDM: "2-Aminosulfonyl-N,N-dimethylnicotin",
  CDEPA: "2-Chloro-N-(2,6-diethylphenyl)acetamide",
  BENZENA: "2-ethyl-6-methylaniline",
  DEA: "2,6-Diethylaniline",
  "3KETCA": "3-Ketocarbofuran",
  "34DCLA": "3,4-dichloroaniline",
  "4ISPRO": "4-Isopropylaniline",
  "44DCBP": "4,4'-Dichlorobenzophenone",
  ALDSN: "Aldicarbe sulfoné",
  ALDSY: "Aldicarbe sulfoxyde",
  AMPA: "AMPA",
  AD2H: "Atrazine déisopropyl-2-hydroxy",
  ADET: "Atrazine déséthyl",
  ADETD: "Atrazine déséthyl déisopropyl",
  ADET2: "Atrazine déséthyl-2-hydroxy",
  A2H: "Atrazine-2-hydroxy",
  ADSP: "Atrazine-déisopropyl",
  AUSN: "2-[(carbamimidoylcarbamoyl)sulfamoyl]-N,Ndimethylpyridine-3-carboxamid",
  KEP5BH: "Chlordecone 5b Hydro",
  "2CP": "Chlorophénol-2",
  "4CP": "Chlorophénol-4",
  CLTHAR6: "Chlorothalonil métabolite R611965",
  CLTHSYN: "Chlorothalonil métabolite SYN507900",
  CLTHA4H: "Chlorothalonil-4-hydroxy",
  CMBA: "CMBA",
  DDD24: "DDD-2,4'",
  DDD44: "DDD-4,4'",
  DDE24: "DDE-2,4'",
  DDE44: "DDE-4,4'",
  DMTE: "Deméton S méthyl sulfoné",
  "D-CTOL": "Desméthyl-chlortoluron",
  PIRIDM: "Desmethyl-pirimicarb",
  IPPMU: "Desméthylisoproturon",
  NORFLDM: "Desmethylnorflurazon",
  "24DCP": "Dichlorophénol-2,4",
  DC42443: "N-(2,6-dimethylphenyl)-N-(2-methoxyethyl) acétamide",
  OXADIM: "Diméthachlore OXA",
  ENDOS: "Endosulfan sulfate",
  ENDRAL: "Endrine aldéhyde",
  ETSN: "Ethiofencarb sulfone",
  ETSY: "Ethiofencarb sulfoxyde",
  ETU: "Ethylenethiouree",
  ETNUR: "Ethyleneuree",
  FIPRO01: "Fipronil désulfinyl",
  FIPRO03: "Fipronil sulfide",
  FIPRO02: "Fipronil sulfone",
  OXAFLU: "Flufénacet OXA",
  HEPE: "Heptachlore époxyde",
  HEPEC: "Heptachlore époxyde cis",
  HEPET: "Heptachlore époxyde trans",
  "3HXC": "Hydroxycarbofuran-3",
  TBZH: "Hydroxyterbuthylazine",
  MALAOX: "Malaoxon",
  MESUO: "Methiocarb sulfone",
  MESUY: "Methiocarb sulfoxyde",
  CARB3M: "Methyl-3-hydroxylphenylcarbamate",
  MTC3577: "Métolachlore métabolite CGA 357704",
  MTC3682: "Métolachlore métabolite CGA 368208",
  DMST: "N,N-Dimet-tolylsulphamid",
  DMSA: "N,N-diméthyl-N'-phénylsulfamide",
  OCHA: "Oxychlordane",
  PARAOX: "Paraoxon",
  PARM: "Paraoxon méthyl",
  "12345CB": "Pentachlorobenzène",
  PHRTS: "Phorate Sulfone",
  PHTHA: "Phthalimide",
  PIFODM: "Pirimicarb formamido desméthyl",
  PPCHL_E: "Propachlore ESA",
  PPCHL_O: "Propachlore OXA",
  PRP2H: "Propazine 2-hydroxy",
  PTU: "Propylene thiouree",
  PRODES: "Prothioconazole-Desthio",
  ACETSAA: "SAA Acétochlore",
  SBAZ2H: "Sebuthylazine 2-hydroxy",
  SEBUT2H: "Sebuthylazine déséthyl",
  SHYD: "Simazine hydroxy",
  DD_S2: "Somme DDD44',DDE44',DDT24',DDT44'",
  DITHIO1: "Somme métabolites Dithiocarbamates",
  TBZDES: "Terbuthylazin déséthyl",
  TBZDESH: "Terbuthylazin déséthyl-2-hydroxy",
  TBZLM6: "Terbuthylazine métabolite LM6",
  THPL: "Tétrahydrophthalimide",
  TSON: "Thiofanox sulfone",
  TSXY: "Thiofanox sulfoxyde",
  TRAZ2H: "Trietazine 2-hydroxy",
  TRAZDE: "Trietazine desethyl",
  DDVP: "Dichlorvos",
  DIAZ: "Diazinon",
  CYANZ: "Cyanazine",
  SCT: "Sulcotrione",
  CFVP: "Chlorfenvinphos",
  CYM: "Cymoxanil",
  KEPONE: "Chlordécone",
  SMZ: "Simazine",
  MCPA: "2,4-MCPA",
  HCHG: "HCH gamma (lindane)",
  TERBU: "Terbutryne",
  AMNTZ: "Aminotriazole",
  CARBR: "Carbofuran",
  DSEB: "Dinoseb",
  FSLZ: "Flusilazol",
  MTHION: "Méthidathion",
  TBZ: "Terbuthylazin",
  DIQDBMD: "Diquat dibromide",
  FOMESAF: "Fomesafen",
  ISP: "Isoproturon",
  FPPMP: "Fenpropimorphe",
  LNR: "Linuron",
  PARTHM: "Parathion méthyl",
  MLNR: "Monolinuron",
  MCPP: "Fénoprop",
  MTC: "Métolachlore",
  ACETOCH: "Acétochlore",
  FNP: "Mécoprop",
  OXDZ: "Oxadiazon",
  PSFC: "Prosulfocarbe",
  GFST: "Glufosinate",
  PROM: "Prométhrine",
  GFSTNH3: "Glufosinate-ammonium",
  FLUTHI: "Flufenacet",
  IOXY: "Ioxynil",
  HXCZ: "Hexaconazole",
  PRQT: "Paraquat",
  DIU: "Diuron",
  THISUME: "Thifensulfuron méthyl",
  MESOTRI: "Mésotrione",
  MTBR: "Métobromuron",
  DCAMB: "Dicamba",
  CTOL: "Chlortoluron",
  "24D": "2,4-D",
  CLMPE: "Chlorpyriphos éthyl",
  TRBNURO: "Tribenuron-méthyle",
  DICHLB: "Dichlobénil",
  BMUCON: "Bromuconazole",
  DITHIAN: "Dithianon",
  VCLZ: "Vinchlozoline",
  THIR: "Thirame",
  MTBZ: "Métribuzine",
  FLAZASU: "Flazasulfuron",
  FLUXA: "Fluxapyroxad",
  CLTHAL: "Chlorothalonil",
  FPRO: "Fenpropidin",
  ATRZ: "Atrazine",
  PROP: "Propazine",
  DMTH: "Diméthénamide",
  CBDZ: "Carbendazime",
  METACET: "Métaldéhyde",
  NFZ: "Norflurazon",
  PROSULF: "Prosulfuron",
  ISOXAFL: "Isoxaflutole",
  PPX: "Propoxur",
  DMTHP: "Dimethenamide-p",
  DALAPON: "Dalapon 85",
  CHLOMEQ: "Chloroméquat chlorure (utiliser CLMQ)",
  THBZ: "Thiabendazole",
  IMAZ: "Imazalile",
  FCLRD: "Flurochloridone",
  TBCZ: "Tébuconazole",
  PMPA: "Cyprodinil",
  MALTH: "Malathion",
  FENAMID: "Fénamidone",
  PYRD: "Pyridate",
  PRPZ: "Propyzamide",
  DCP: "Dichlorprop",
  PPCNZ: "Propiconazole",
  BOSCALI: "Boscalid",
  DMTM: "Diméthomorphe",
  IMIDA: "Imidaclopride",
  CBTM: "Carbétamide",
  IMAT: "Imazaméthabenz",
  FLUTO: "Flutolanil",
  DIMEFUR: "Diméfuron",
  PROPAMO: "Propamocarbe",
  METAL: "Métalaxyle",
  METALM: "Méfénoxam",
  NAPR: "Napropamide",
  PDM: "Pendiméthaline",
  BTZ: "Bentazone",
  CLDZ: "Chloridazone",
  DIMETAC: "Dimétachlore",
  CLETHO: "Clethodime",
  BRMCL: "Bromacil",
  CLOMAZO: "Clomazone",
  AZOXYST: "Azoxystrobine",
  CLOPY: "Clopyralid",
  DFF: "Diflufénicanil",
  AMIDOSU: "Amidosulfuron",
  PPBTX: "Piperonil butoxide",
  MEPIQUA: "Mepiquat",
  IMETS: "Metsulfuron méthyl",
  ETFS: "Ethofumésate",
  DTFC: "Diethofencarbe",
  FPYR: "Fluroxypir",
  FPYRM: "Fluroxypir-meptyl",
  NICOSUL: "Nicosulfuron",
  MESOSUL: "Mésosulfuron-méthyl",
  IMAMOX: "Imazamox",
  EFOSITE: "Fosetyl-aluminium",
  HCHB: "HCH béta",
  ANTHRAQ: "Anthraquinone (pesticide)",
  IPD: "Iprodione",
  PROCYM: "Procymidone",
  ALCL: "Alachlore",
  ETDMR: "Ethidimuron",
  TAM: "Tébutam",
  FNUR: "Fénuron",
  MTBZTZ: "Métabenzthiazuron",
  SECB: "Secbuméton",
  NBR: "Néburon",
  TFU: "Thiazfluron",
  LFLAM: "Flamprop-isopropyl",
  CCHOLIN: "Chlorure de choline",
  METZCL: "Métazachlore",
  MTMI: "Métamitrone",
  HXZN: "Hexazinone",
  TERBM: "Terbuméton",
  IXB: "Isoxaben",
  TCPY: "Triclopyr",
  PCLR: "Prochloraze",
  ODX: "Oxadixyl",
  EPOXCZ: "Epoxyconazole",
  PMC: "Pyrimicarbe",
  GPST: "Glyphosate",
  PRMTN: "Pyriméthanil",
  CPCNZ: "Cyproconazol",
  METCONA: "Metconazol",
  DTERB: "Dinoterbe",
  QUINMR: "Quimerac",
  FLUDIOX: "Fludioxonil",
  LNCE: "Lenacile",
  CNPA: "Aclonifen",
  CYINE: "Cyperméthrine",
  ORZ: "Oryzalin",
  BRXY: "Bromoxynil",
  TCNZ: "Tétraconazole",
  SPIROX: "Spiroxamine",
  FLURTAM: "Flurtamone",
  IODOSU: "Iodosulfuron-methyl-sodium",
  DIFENOC: "Difénoconazole",
  ALDR: "Aldrine",
  AMTH: "Améthryne",
  BENOXA: "Benoxacor",
  HCHD: "HCH delta",
  HEP: "Heptachlore",
  HEOD: "Dieldrine",
  HCHA: "HCH alpha",
  ACET: "Acétamiprid",
  TRIF: "Trifluraline",
  FIPRO: "Fipronil",
  CLMQ: "Chlormequat",
  CPPH: "Chlorprophame",
  SULFRN: "Sulfosulfuron",
  CYCLOXY: "Cycloxydime",
  MNR: "Monuron",
  DNOC: "Dinitrocrésol",
  DIMTH: "Diméthoate",
  TBTR: "Thébuthiuron",
  CHLPM: "Chlorpyriphos méthyl",
  DCFL: "Dicofol",
  CLOT: "Clothianidine",
  PYRAC: "Pyraclostrobine",
  DDT44: "DDT-4,4'",
  FENBUCO: "Fenbuconazole",
  THIAMET: "Thiamethoxam",
  PYROX: "Pyroxsulame",
  QUINOXY: "Quinoxyfen",
  IMATMET: "Imazaméthabenz-méthyl",
  PRT: "Perméthrine",
  SEBUT: "Sébuthylazine",
  MYCLOSS: "Myclobutanil",
  FORASUL: "Foramsulfuron",
  DMTRY: "Desmétryne",
  TRINEXA: "Trinéxapac-éthyl",
  TRIFLX: "Trifloxystrobine",
  DTINE: "Deltaméthrine",
  CYBUT: "Cybutryne",
  THIACLO: "Thiaclopride",
  KRESOXI: "Kresoxim-méthyle",
  HCHTOT4: "HCH alpha+beta+delta+gamma",
  CANT: "Chlorantraniliprole",
  BFNX: "Bifenox",
  TLL: "Triallate",
  DDT24: "DDT-2,4'",
  FLOAMD: "Flonicamide",
  FTFL: "Flutriafol",
  "245T": "2,4,5-T",
  BFLN: "Benfluraline",
  FENOXY: "Fenoxycarbe",
  DIQUAT: "Diquat",
  FLORAS: "Florasulam",
  CBRYL: "Carbaryl",
  CHINE: "Lambda Cyhalothrine",
  MCPB: "2,4-MCPB",
  BFINE: "Bifenthrine",
  TRSULFM: "Triflusulfuron-methyl",
  PACLOBU: "Paclobutrazole",
  TDMF: "Triadiméfon",
  PARTH: "Parathion éthyl",
  MTZ: "Métoxuron",
  OXYFLUO: "Oxyfluorfene",
  DFB: "Diflubenzuron",
  TEFLUTH: "Tefluthrine",
  EPROP: "Ethoprophos",
  ASULAME: "Asulame",
  METRAF: "Metrafenone",
  BIX: "Bixafen",
  ENDOT: "Endosulfan total",
  ZOXAMID: "Zoxamide",
  BAX: "Bénalaxyl",
  PENCYCU: "Pencycuron",
  TRITO: "Tritosulfuron",
  PYRMM: "Pyrimiphos méthyl",
  FLUAZB: "Fluazifop butyl",
  FENHEXA: "Fenhexamid",
  MTHC: "Méthiocarb",
  ACIFLUO: "Acifluorfen",
  RSFU: "Rimsulfuron",
  PICOX: "Picoxystrobine",
  TCM: "Thiencarbazone-methyl",
  "24DB": "2,4-DB",
  FOSTHIA: "Fosthiazate",
  PYMET: "Pymétrozine",
  PROTHIO: "Prothioconazole",
  PICLO: "Piclorame",
  FLUPYR: "Flupyrsulfuron-méthyle",
  MTMY: "Méthomyl",
  PINOX: "Pinoxaden",
  PHM: "Phoxime",
  FLUQUIN: "Fluquinconazole",
  IPROVAL: "Iprovalicarb",
  FMTH: "Fluométuron",
  PHOSL: "Phosalone",
  ENDR: "Endrine",
  ACYINE: "Alphaméthrine",
  MOL: "Molinate",
  FLPIDE: "Fluopicolide",
  OXDM: "Oxydéméton méthyl",
  CYAZOF: "Cyazofamide",
  PROMN: "Prométon",
  FENOXA: "Fénoxaprop-éthyl",
  PECNZ: "Penconazole",
  BTRON: "Buturon",
  TDMN: "Triadimenol",
  PPCHL: "Propachlore",
  MTX: "Méthoxychlore",
  BTTNL: "Bitertanol",
  TITCNZ: "Triticonazole",
  CLOQMEX: "Cloquintocet-mexyl",
  PETHO: "Pethoxamide",
  ESFENV: "Esfenvalérate",
  CYSUL: "Cyprosulfamide",
  BRXYOC: "Bromoxynil octanoate",
  DINICO: "Diniconazole",
  CARBOX: "Carboxine",
  TBZDE: "Tébufénozide",
  TFBZURO: "Teflubenzuron",
  FLUAZF: "Fluazifop",
  CPC: "Chlorophacinone",
  SITN: "Simétryne",
  CYROMAZ: "Cyromazine",
  MEFENPD: "Mefenpyr diethyl",
  BROMADI: "Bromadiolone",
  QUIZO: "Quizalofop",
  FERI: "Fénarimol",
  THIOPM: "Thiophanate méthyl",
  OXYM: "Oxamyl",
  THIODIC: "Thiodicarbe",
  THIDIAZ: "Thidiazuron",
  BUT: "Butraline",
  CSFU: "Chlorsulfuron",
  CLODINA: "Clodinafop-propargyl",
  MPNI: "Mépanipyrim",
  COMLI: "Cycluron",
  FXAS: "Fluoxastrobine",
  PROPAQU: "Propaquizafop",
  CADUSAF: "Cadusafos",
  AZINE: "Azinphos éthyl",
  CLAHA: "Chlordane alpha",
  TEMBO: "Tembotrione",
  FOLPEL: "Folpel",
  TBPYR: "Tébufenpyrad",
  FLUAZN: "Fluazinam",
  DCFMT: "Diclofop méthyl",
  IALDR: "Isodrine",
  TRIASUL: "Triasulfuron",
  FENIT: "Fenitrothion",
  HXFLUMU: "Hexaflumuron",
  CYFLTH: "Cyfluthrine",
  CARFENE: "Carfentrazone éthyle",
  CLBROMU: "Chlorbromuron",
  FLUXR: "Flufénoxuron",
  VMDT: "Vamidothion",
  ADC: "Aldicarbe",
  OOA: "Ométhoate",
  CHLX: "Chloroxuron",
  HALOX: "Haloxyfop",
  MCPO: "Mecoprop-1-octyl ester",
  HCHE: "HCH epsilon",
  FOSETYL: "Fosetyl",
  CLAHB: "Chlordane béta",
  PYRX: "Pyrifénox",
  IMAZAPY: "Imazapyr",
  ETHION: "Ethion",
  FLUMIOX: "Flumioxazine",
  EKALUX: "Quinalphos",
  METOSUL: "Métosulam",
  TTAZINE: "Trietazine",
  BUPIRI: "Bupirimate",
  ETHPH: "Ethephon",
  HTZ: "Hexythiazox",
  TAUFLU: "Fluvalinate-tau",
  FENTH: "Fenthion",
  BENFURA: "Benfuracarbe",
  PPIT: "Propargite",
  TERB: "Terbuphos",
  DCLORMI: "Dichlormide",
  FONO: "Fonofos",
  DMTHY: "Dimethametryn",
  MEFENA: "Mefenacet",
  BEFLU: "Beflubutamide",
  HXPEE: "Haloxyfop éthoxyéthyl",
  MANDIP: "Mandipropamide",
  FEINE: "Fenpropathrine",
  SIDURON: "Siduron",
  TCF: "Trichlorfon",
  ACNT: "Acrinathrine",
  FLUOPYR: "Fluopyram",
  AZACONA: "Azaconazole",
  TRFLUM: "Triflumuron",
  HYDMAL: "Hydrazide maleïque",
  TCVP: "Tétrachlorvinphos",
  DCFT: "Dichlofenthion",
  PNCB: "Quintozène",
  QUIZOET: "Quizalofop éthyle",
  TRIAZ: "Triazoxide",
  "34DCPA": "Propanil",
  INDOXAC: "Indoxacarbe",
  TRZAMAT: "Triazamate",
  PYRIDAB: "Pyridabène",
  DIPHAM: "Diphenylamine",
  CHINOME: "Chinométhionate",
  DCHLOPH: "Dichorophène",
  SPINO: "Spinosad",
  THIOBEN: "Thiobencarde",
  PPMD: "Phosphamidon",
  BEND: "Bendiocarbe",
  CYFLU: "Cyflufenamide",
  NUARIMO: "Nuarimol",
  FLURIDO: "Fluridone",
  FAMOXAD: "Famoxadone",
  TRIFORI: "Triforine",
  FURALAX: "Furalaxyl",
  TMT: "Thiométon",
  IOXYOCT: "Ioxynil octanoate",
  PMPT: "Pyrimiphos éthyl",
  DCPADH: "Chlorthal-diméthyl",
  SPITET: "Spirotetramat",
  AZIMSUL: "Azimsulfuron",
  TBIL: "Terbacile",
  MVPH: "Mévinphos",
  DLL: "Diallate",
  BRPH: "Bromophos méthyl",
  CAPT: "Captane",
  PENOXU: "Penoxsulam",
  DSYST: "Disyston",
  PHOSMET: "Phosmet",
  PHENM: "Phenmédiphame",
  DNOCP: "Dinocap",
  AZIN: "Azinphos méthyl",
  DMTSM: "Demeton S méthyl",
  TRCYCLA: "Tricyclazole",
  UNCAZ: "Uniconazole",
  ETOF: "Etofenprox",
  FENCL: "Fenchlorphos",
  PZP: "Pyrazophos",
  DIMOX: "Dimoxystrobine",
  IMAZAQU: "Imazaquine",
  FLURPRI: "Flurprimidol",
  TBZMETA: "Terbuthylazin et ses métabolites",
  SMETOLA: "S-Métolachlore",
  PICONA: "Picolinafen",
  AZAMETI: "Azamétiphos",
  SILTF: "Silthiofam",
  BRMTH: "Bioresmethrine",
  BROMOE: "Bromophos éthyl",
  PPTP: "Propétamphos",
  EPTC: "EPTC",
  PHRT: "Phorate",
  IPCONA: "Ipconazole",
  HALOXYR: "Haloxyfop-méthyl (R)",
  TLFND: "Tolylfluanide",
  IOXYM: "Ioxynil-méthyl",
  CLMP: "Chlorméphos",
  DICOUM: "Difenacoum",
  COUMATE: "Coumatétralyl",
  PPHM: "Prophame",
  COUMAF: "Coumafène",
  TRZPH: "Triazophos",
  DILONE: "Difethialone",
  HEPTENO: "Hepténophos",
  DCPP: "Dichlorprop-P",
  ISOXADI: "Isoxadifen-éthyle",
  OFURACE: "Ofurace",
  TTDIFON: "Tetradifon",
  MEPRONI: "Mépronil",
  PYRPF: "Pyriproxyfen",
  FURATHI: "Furathiocarbe",
  OXDG: "Oxadiargyl",
  ISPV: "Isofenvos",
  LUFENUR: "Lufénuron",
  BUPROFZ: "Buprofézine",
  COUM: "Coumaphos",
  IODOFEN: "Iodofenphos",
  PPCBS: "Propoxycarbazone-sodium",
  CBPT: "Carbophénotion",
  FVAL: "Fenvalérate",
  TEDP: "Sulfotepp",
  PROFENO: "Profénofos",
  FLUAZPB: "Fluazifop-P-butyl",
  NITROF: "Nitrofène",
  FENOB: "Fenobucarbe",
  CHLFLUA: "Chlorfluazuron",
  METIL: "Dimétilan",
  ROTENON: "Roténone",
  ETHIOPH: "Ethiophencarbe",
  CINOSUL: "Cinosulfuron",
  ETXSUL: "Ethoxysulfuron",
  BENSULH: "Bensulfuron-methyl",
  AMITZ: "Amitraze",
  "643PYRD": "Pyridafol",
  DIFXUR: "Difenoxuron",
  MEFLUID: "Méfluidide",
  SEDAX: "Sedaxane",
  SFOMTH: "Sulfomethuron-methyl",
  CLRMTH: "Chlorimuron-ethyl",
  PYRAZET: "Pyrazosulfuron éthyl",
  DAIMURO: "Daimuron",
  ETHAMH: "Ethametsulfuron-methyl",
  HASULM: "Halosulfuron-methyl",
  OXSULFH: "Oxasulfuron",
  FCLURO: "Forchlorfenuron",
  IMBCAZ: "Imibenconazole",
  ETRIM: "Etrimfos",
  CHLORB: "Chlorbufame",
  ACP: "Acéphate",
  METHACR: "Méthacrifos",
  PYRAZXF: "Pyrazoxyfen",
  ASM: "Acibenzolar s méthyl",
  MTHDP: "Méthamidophos",
  MCPPP: "Mécoprop-p",
  ABATE: "Téméphos",
  SPINOA: "Spinosyne A",
  SPINOD: "Spinosyne D",
  DAMZD: "Daminozide",
  BCYFLTH: "Betacyfluthrine",
  PHENTHO: "Phentoate",
  QUINO: "Quinoclamine",
  CPT: "Captafol",
  AZODRIN: "Monocrotophos",
  ATRATN: "Atraton",
  TOLM: "Tolclofos-methyl",
  CLTHIO: "Chlorthiophos",
  DODINE: "Dodine",
  MTFEN: "Methoxyfenoside",
  BENSLD: "Bensulide",
  PRETILA: "Pretilachlore",
  "24DIE": "2,4-D-isopropyl ester",
  AMETO: "Ametoctradine",
  BRPPL: "Bromopropylate",
  DIOXA: "Dioxacarbe",
  PROQUI: "Proquinazid",
  DEHAME: "Desmediphame",
  FLAMPM: "Flamprop-méthyl",
  MIR: "Mirex",
  ATRZMET: "Atrazine et ses métabolites",
  ISAZO: "Isazophos",
  TCBAZ: "Tiocarbazil",
  PROME: "Promécarbe",
  HYMEX: "Hymexazol",
  AMINP: "Aminopyralid",
  CLRNB: "Chloroneb",
  DICRO: "Dicrotophos",
  BUTIL: "Butilate",
  CYCLOA: "Cycloate",
  PIPERO: "Piperophos",
  ANILO: "Anilophos",
  PYDAP: "Pyridaphenthion",
  ISOPC: "Isoprocarb",
  CYHABU: "Cyhalofop butyl",
  BENVCI: "Benthiavalicarbe-isopropyl",
  ZCYINE: "Zetacypermethrine",
  NALED: "Naled",
  DCLFNFD: "Dichlofluanide",
  PYRETHR: "Pyréthrine",
  QUIZPE: "Quizalofop-p-éthyl",
  AMINC: "Aminocarbe",
  CLAN: "Chlordane",
  TRIMC: "Trimethacarbe",
  FNFS: "Phénamiphos",
  MCP244: "MCPP-2,4,4-trimethylpentyl ester",
  MCP2OE: "MCPP-2 otyl ester",
  MCPA1B: "MCPA-1-butyl ester",
  MCP2EE: "MCPP- 2-ethylhexyl ester",
  MCP2BE: "MCPP-2-butoxyethyl ester",
  MCPNIB: "Mecoprop-n/iso-butyl ester (mélange)",
  MCPME: "MCPP-methyl ester",
  PYCL: "Pyraclofos",
  FENIS: "Fenizon",
  EPN: "EPN",
  PYFE: "Pyraflufen éthyl",
  ABAMECT: "Abamectin",
  VALIF: "Valifenalate",
  FENOT: "Fenothiocarbe",
  PRXP: "Proximphan",
  DIMEP: "Dimépipérate",
  BUTAM: "Butamifos",
  MEPHOS: "Mephosfolan",
  EDIF: "Edifenphos",
  PYBUT: "Pyributicarb",
  PRPA: "Propaphos",
  DIMET: "Diméthylvinphos",
  FAMP: "Famphur",
  TECNAZ: "Tecnazene",
  TETRAS: "Tetrasul",
  CLFSON: "Chlorfenson",
  FRAZ: "Furilazole",
  PROFOX: "Profoxydim",
  FENAZAQ: "Fénazaquin",
  "4C2MPH": "Chloro-4 Méthylphénol-2",
  FCLAZE: "Fenchlorazole ethyl",
  TCLNAT: "Trichloronat",
  BUFENC: "Bufencarbe",
  CRUFOM: "Crufomate",
  CROTOX: "Crotoxyphos",
  SULPRO: "Sulprofos",
  ALLYXY: "Allyxycarbe",
  TEBUPI: "Tebupirimfos",
  MEXAC: "Mexacarbate",
  MCPAEE: "2,4-D 2-Ethylhexyl",
  MERPHO: "Merphos",
  AMIDIT: "Amidithion",
  CYANFP: "Cyanofenphos",
  IBP: "Iprobenfos (IBP)",
  AMIPRM: "Amiprofos-methyl",
  MECARB: "Mecarbam",
  ISOXAT: "Isoxathion",
  SETHOX: "Sethoxydim",
  MTOLC: "Metolcarb",
  TLINE: "Tralométhrine",
  EMAM: "Emamectine",
  MITC: "Méthyl isothiocyanate",
  FNAP: "Fénoxaprop",
  "24DME": "2,4-D-methyl ester",
  MDNOCP: "Meptyldinocap",
  MANC: "Mancozèbe",
  DMT: "Déméton",
  KARBUT: "Karbutilate",
  ISMTZN: "Isomethiozin",
  AZYPRO: "Aziprotryne",
  TBUC: "Terbucarb",
  FENFU: "Fenfuran",
  FORME: "Formétanate",
  SYSTOX: "Déméton-O",
  CLOFEN: "Clofentézine",
  THIOPE: "Thiophanate ethyl",
  DMTS: "Déméton-S",
  MCPA2E: "MCPA-ethyl ester",
  PRTT: "Perméthrine-trans",
  PRTC: "Perméthrine-cis",
  DBCP: "Dibromo-1,2-chloro-3propane",
  DPLLTH: "Dépallethrine",
  CNEB: "Chloroneb",
  BIFE: "Bifenazate",
  BENO: "Benomyl",
  PRIM: "Primisulfuron méthyl",
  EU: "Ethyluree (pesticide)",
  THIOCY2: "Thiocyclam hydrogen oxalate",
  FENOXP: "Fenoxaprop-p-ethyl",
  HMTRIM: "heptamethyltrisiloxane modifié",
  TMETH: "Tétraméthrine",
  CLAQ: "Chlordane gamma",
  CYTHIO: "Cythioate",
  BAM: "Benalaxyl-M",
  ACEQ: "Acequinocyl",
  ETOXAZ: "Etoxazole",
  SDDTDE: "Somme  DDT, DDD, DDE",
  CARBOSU: "Carbosulfan",
  DDTS: "DDT somme",
  DCBUT: "Diclobutrazol",
  TNC: "Trans-nonachlore",
  PARATH: "Parathions (éthyl+méthyl)",
  TFX: "Thiofanox",
  SPIDIC: "Spirodiclofen",
  BZDN: "Benzidine (pesticide)",
  CLTHIAM: "Chlorthiamide",
  MCPAME: "MCPA-methyl ester",
  ZIRA: "Zirame",
  DITALM: "Ditalimfos",
  TERBMME: "Terbuméton et ses métabolites",
  MCPABE: "2,4-D-butotyl",
  HCET: "Hexachloroéthane (pesticide)",
  NPA: "Naptalame",
  TRIADEM: "Tridemorphe",
  SULFOSA: "Sulfosate",
  TOXAPHE: "Toxaphène",
  BANCOL: "Bensultap",
  CINIDON: "Cinidon-ethyl",
  SPINE: "Spinetoram",
  SPIMES: "Spiromesifen",
  MILB: "Milbemectin",
  ISNRRN: "Isonoruron",
  FENP: "Fenpyroximate",
  PHNTN: "Phenothrine",
  "13DCP": "Dichloropropane-1,3",
  PTPD: "Penthiopyrad",
  FMTHN: "Formothion",
  PHDC: "Prohexadione-calcium",
  HALM: "Halauxifen-methyl",
  CYTP: "Cyantraniliprole",
  AZA: "Azadirachtin",
  SULFO: "Sulfoxaflor",
  MDB: "Mandestrobine",
  OTP: "Oxathiapiprolin",
  ISOF: "Isofetamid",
  PYRF: "Pyriofenone",
  FPDF: "Flupyradifurone",
  GAINE: "Gamma Cyhalothrine",
  DCPA: "Chlorthal",
  ISCBMD: "Isocarbamide",
  ISCBPS: "Isocarbophos",
  BTCBX: "Butocarboxim",
  CARPRO: "Carpropamide",
  DIPHNM: "Diphenamide",
  PYROQU: "Pyroquilon",
  ISPTLN: "Isoprothiolane",
  PYRACA: "Pyracarbolid",
  BRM: "Bromométhane",
  DMTT: "Dazomet",
  MBT: "Monobutylétain cation (pesticide)",
  BROD: "Brodifacoum",
  CYHAL: "Cyhalothrine",
  PRTF: "Prothiofos",
  MANEB: "Manèbe",
  FENBUOX: "Fenbutatin oxyde",
  RESM: "Resmethrine",
  NHFOSAM: "Fosamine ammonium",
  PCH: "Propamocarbe hydrochloride",
  PRQTDC: "Paraquat dichloride",
  MFTC: "Méfentrifluconazole",
  MCPA2EH: "MCPA-2-ethylhexyl",
  MCPABU: "MCPA-butotyl",
  MEPIQU1: "Mepiquat chlorure (utiliser MEPIQUA)",
  AMISUL: "Amisulbron",
  PESTOT: "Total pesticides",
};

export function getParameterName(code: string): string {
  return PARAMETER_NAMES[code] || code;
}
