version: 2

seeds:
  - name: mapping_categories_v2
    description: "nouveau Table de mapping des catégories de paramètres de qualité de l'eau."
    columns:
      - name: cdparametresiseeaux
        description: "Code SISE-Eaux (Système d'Information des services Santé-Environnement Eaux) du paramètre"
      - name: cdparametre
        description: "Code SANDRE (Service National d'Administration des Données et Référentiels sur l'Eau) du paramètre"
      - name: libmajparametre
        description: "Nom du paramètre en majuscule"
        tests:  
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: VARCHAR
      - name: libminparametre
        description: "Nom du paramètre en minuscule"
        tests:  
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: VARCHAR
      - name: casparam
        description: "Code CAS (Chemical Abstracts Service) de la substance chimique"
      - name: categorie
        description: "Catégorie du paramètre (pesticides, nitrites, etc.)"
        tests:
          - not_null 
      - name: souscat
        description: "Sous-categorie"
      - name: detailsouscat
        description: "Detail de sous-categorie"
      - name: limitequal
        description: "Limite(s) de qualité du paramètre concerné en vigueur au moment du prélèvement pour le type d'eau considéré."
      - name: commentlimitquality
        description: " Commentaire limite qualité"
      - name: unite
        description: "Unité de valeur"
      - name: valsanitaire1	
        description: "valuer de sanitaire 1"
      - name: commentvalsanitaire1
        description: "Commentaire sur la valeur sanitaire 1"
      - name: valsanitaire2
        description: "Valeur sanitaire 2"
      - name: commentvalsanitaire2
        description: "Commentaire sur la valeur sanitaire 2"


  - name: mapping_categories
    description: "Table de mapping des catégories de paramètres de qualité de l'eau."
    columns:
      - name: cdparametresiseeaux
        description: "Code SISE-Eaux (Système d'Information des services Santé-Environnement Eaux) du paramètre"
      - name: cdparametre
        description: "Code SANDRE (Service National d'Administration des Données et Référentiels sur l'Eau) du paramètre"
      - name: libmajparametre
        description: "Nom du paramètre en majuscule"
      - name: libminparametre
        description: "Nom du paramètre en minuscule"
      - name: casparam
        description: "Code CAS (Chemical Abstracts Service) de la substance chimique"
      - name: categorie
        description: "Catégorie du paramètre (pesticides, nitrites, etc.)"
        tests:
          - not_null