services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - K6_OUT=${K6_OUT:-influxdb=http://influxdb:8086}
    command: run tests/smoke.js
    depends_on:
      - influxdb

  # Optional: InfluxDB for storing results
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb

  # Optional: Grafana for visualizing results
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
